version: "3"
services:
  front:
    container_name: "connect"
    build:
      context: ../
      dockerfile: connect_docker/Dockerfile
    ports:
      - "4060:3000"
    restart: always
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ../app:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
